pull_request_rules:
  - name: Automatic merge on approval
    conditions:
      - author=scala-steward
      - status-success=continuous-integration/jenkins/pr-merge
    actions:
      merge:
        method: squash
        strict: smart
