version: "2.4"
services:
  api:
    image: "granary-api:${GIT_COMMIT}"
    build:
      context: ./api
      dockerfile: Dockerfile

  api-migrations:
    image: "granary-api-migrations:${GIT_COMMIT}"
    build:
      context: ./database
      dockerfile: Dockerfile.migrations

  calculate-water:
    image: "granary-calculate-water:${GIT_COMMIT}"

  shellcheck:
    image: koalaman/shellcheck:stable
    volumes:
      - ./:/usr/local/src
    working_dir: /usr/local/src

  terraform:
    image: quay.io/azavea/terraform:0.12.13
    volumes:
      - ./:/usr/local/src
      - $HOME/.aws:/root/.aws:ro
    environment:
      - AWS_PROFILE
      - AWS_DEFAULT_REGION=us-east-1
      - GIT_COMMIT=${GIT_COMMIT:-latest}
      - GRANARY_DEBUG=1
      - GRANARY_SETTINGS_BUCKET=${GRANARY_SETTINGS_BUCKET:-rasterfoundry-production-config-us-east-1}
    working_dir: /usr/local/src
    entrypoint: bash
