version: "2.3"
services:
  database:
    image: quay.io/azavea/postgis:2.3-postgres9.6-slim
    environment:
      - POSTGRES_USER=granary
      - POSTGRES_PASSWORD=granary
      - POSTGRES_DB=granary
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "granary"]
      interval: 3s
      timeout: 3s
      retries: 3
      start_period: 5s

  api:
    image: openjdk:11-jdk
    command:
      - "api/run"
    depends_on:
      database:
        condition: service_healthy
    entrypoint: java
    command:
      - "-jar"
      - "granary-api-assembly.jar"
    environment:
      - AWS_PROFILE
      - ENVIRONMENT=development
      - POSTGRES_URL=jdbc:postgresql://database.service.internal/
      - POSTGRES_NAME=granary
      - POSTGRES_USER=granary
      - POSTGRES_PASSWORD=granary
      - GRANARY_TRACING_SINK=jaeger
    links:
      - database:database.service.internal
      - jaeger:jaeger.service.internal
      - xray:xray.service.internal
    ports:
      - "8080:8080"
    volumes:
      - ./:/opt/granary/
      - $HOME/.sbt:/root/.sbt
      - $HOME/.coursier:/root/.coursier
      - ./.bintray:/root/.bintray
      - $HOME/.ivy2:/root/.ivy2
      - $HOME/.aws:/root/.aws:ro
    working_dir: /opt/granary/api/target/scala-2.12/

  sbt:
    image: openjdk:11-jdk
    depends_on:
      database:
        condition: service_healthy
    links:
      - database:database.service.internal
    environment:
      - AWS_PROFILE
      - POSTGRES_URL=jdbc:postgresql://database.service.internal/
      - POSTGRES_NAME=granary
      - POSTGRES_USER=granary
      - POSTGRES_PASSWORD=granary
      - COURSIER_CACHE=/root/.coursier
    volumes:
      - ./:/opt/granary
      - $HOME/.sbt:/root/.sbt
      - $HOME/.coursier:/root/.coursier
      - ./.bintray:/root/.bintray
      - $HOME/.ivy2:/root/.ivy2
      - $HOME/.aws:/root/.aws:ro
    working_dir: /opt/granary/
    entrypoint: ./sbt

  api-migrations:
    image: boxfuse/flyway:5.2.4
    environment:
      - FLYWAY_DRIVER=org.postgresql.Driver
      - FLYWAY_URL=jdbc:postgresql://database.service.internal/granary
      - FLYWAY_USER=granary
      - FLYWAY_PASSWORD=granary
      - FLYWAY_LOCATIONS=filesystem:/opt/granary/database/src/main/resources/db
      - FLYWAY_SCHEMAS=public
      - FLYWAY_BASELINE_ON_MIGRATE=true
    depends_on:
      database:
        condition: service_healthy
    links:
      - database:database.service.internal
    volumes:
      - ./:/opt/granary

  jaeger:
    image: jaegertracing/all-in-one:1.8
    expose:
      - 5775/udp
      - 6831/udp
      - 6832/udp
      - 5778
      - 16686
      - 14268
      - 9411
    ports:
      - 16686:16686
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411

  xray:
    image: amazon/aws-xray-daemon
    volumes:
      - $HOME/.aws:/root/.aws:ro
    ports:
      - 2000
    entrypoint: "/usr/bin/xray"
    command:
      - "-t"
      - "0.0.0.0:2000"
      - "-b"
      - "0.0.0.0:2000"
