addSbtPlugin("org.lyranthe.sbt"          % "partial-unification"      % "1.1.2")
addSbtPlugin("io.github.davidgregory084" % "sbt-tpolecat"             % "0.1.10")
addSbtPlugin("io.spray"                  % "sbt-revolver"             % "0.9.1")
addSbtPlugin("org.scalameta"              % "sbt-scalafmt"             % "2.0.0")
addSbtPlugin("com.sksamuel.scapegoat"    %% "sbt-scapegoat"           % "1.1.0")
addSbtPlugin("ch.epfl.scala"             % "sbt-scalafix"             % "0.9.11")
addSbtPlugin("com.eed3si9n"              % "sbt-assembly"             % "0.14.10")
addSbtPlugin("org.jmotor.sbt"            % "sbt-dependency-updates"   % "1.2.1")
