#!/bin/bash

set -e

if [[ -n "${GRANARY_DEBUG}" ]]; then
    set -x
fi

if [[ -n "${GIT_COMMIT}" ]]; then
    GIT_COMMIT="${GIT_COMMIT:0:7}"
else
    GIT_COMMIT="$(git rev-parse --short HEAD)"
fi

function usage() {
    echo -n \
        "Usage: $(basename "$0")
Build application for staging or a release.
"
}

if [ "${BASH_SOURCE[0]}" = "${0}" ]; then
    if [ "${1:-}" = "--help" ]; then
        usage
    else
        docker-compose up -d database

        ./scripts/test

        echo "Building optimized Elm application"
        pushd granary-ui
        elm-app make \
            src/Main.elm \
            --output ../api/src/main/resources/assets/index.html \
            --optimize
        cp -r public/* ../api/src/main/resources/assets/
        popd

        echo "Building JAR for API subproject"
        docker-compose \
            run --rm sbt \
            "api/assembly"

        echo "Building Scala container images"
        GIT_COMMIT="${GIT_COMMIT}" docker-compose \
            -f docker-compose.yml \
            -f docker-compose.ci.yml \
            build api api-migrations
    fi
fi
