#!/bin/bash

set -e

if [[ -n "${GRANARY_DEBUG}" ]]; then
    set -x
fi

function usage() {
    echo -n \
        "Usage: $(basename "$0")
Publish container images to Quay.
"
}

if [[ -n "${GIT_COMMIT}" ]]; then
    GIT_COMMIT="${GIT_COMMIT:0:7}"
else
    GIT_COMMIT="$(git rev-parse --short HEAD)"
fi

if [ "${BASH_SOURCE[0]}" = "${0}" ]; then
    if [ "${1:-}" = "--help" ]; then
        usage
    else
        docker \
            login -u "${QUAY_USER}" -p "${QUAY_PASSWORD}" quay.io

        docker tag "granary-api:${GIT_COMMIT}" \
            "quay.io/raster-foundry/granary-api:${GIT_COMMIT}"
        docker push "quay.io/raster-foundry/granary-api:${GIT_COMMIT}"

        docker tag "granary-api-migrations:${GIT_COMMIT}" \
            "quay.io/raster-foundry/granary-api-migrations:${GIT_COMMIT}"
        docker push "quay.io/raster-foundry/granary-api-migrations:${GIT_COMMIT}"

        # docker tag "granary-calculate-water:${GIT_COMMIT}" \
        #     "quay.io/raster-foundry/granary-calculate-water:${GIT_COMMIT}"
        # docker push "quay.io/raster-foundry/granary-calculate-water:${GIT_COMMIT}"
    fi
fi
