#! /bin/bash

set -e

if [[ -n "${GRANARY_DEBUG}" ]]; then
    set -x
fi

function usage() {
    echo -ne \
         "Usage: $(basename "${0}")
Run linters and tests.
"
}

if [ "${BASH_SOURCE[0]}" = "${0}" ]; then
    if [ "${1:-}" = "--help" ]; then
        usage
    else
        if which shellcheck &>/dev/null; then
            echo "Linting STRTA scripts"
            find ./scripts -type f -print0 | xargs -0 -r shellcheck
        fi

        echo "Execute Scalafix"
        docker-compose \
            run --rm \
            sbt "scalafix --check"

        echo "Execute Scala tests"
        docker-compose \
            run --rm \
            sbt test

    fi
fi
