#!/bin/bash

set -e


if [[ -n "${GRANARY_DEBUG}" ]]; then
    set -x
fi

function usage() {
    echo -n \
         "Usage: $(basename "$0")

Starts servers using docker-compose.
"
}

if [ "${BASH_SOURCE[0]}" = "${0}" ]
then
    case "${1}" in
        --help)
            usage
            ;;
        *)
            echo "Starting API service"
	    bloop run api -- \
		  --with-auth \
		  --db-url "jdbc:postgresql://localhost:5432/"
    esac
fi
