#!/bin/bash

set -e

if [[ -n "${GRANARY_DEBUG}" ]]; then
    set -x
fi

DIR="$(dirname "${0}")/../"

function usage() {
    echo -n \
        "Usage: $(basename "$0")
Attempts to setup the project's development environment.
"
}

function generate_sbtopts() {
    if host nexus.internal.azavea.com; then
        echo "Generating .sbtopts"

        pushd "${DIR}"

        true >.sbtopts

        echo "-Dsbt.override.build.repos=true" >>.sbtopts
        echo "-Dsbt.repository.config=project/repositories" >>.sbtopts

        popd
    fi
}

function setup_elm() {
	echo "Setting up frontend dependencies"
    # make outside of the container to make sure that user owns elm-stuff
    mkdir -p ./granary-ui/elm-stuff
	npm install -g elm elm-format
}

if [ "${BASH_SOURCE[0]}" = "${0}" ]; then
    if [ "${1:-}" = "--help" ]; then
        usage
    elif [ "${1:-}" = "--sbtopts" ]; then
        generate_sbtopts
    else
        setup_elm
        generate_sbtopts
        ./sbt bloopInstall
    fi
fi
