#! /bin/bash

set -e

if [[ -n "${GRANARY_DEBUG}" ]]; then
    set -x
fi

function usage() {
    echo -ne \
        "Usage: $(basename "${0}")
Run linters and tests.
"
}

if [ "${BASH_SOURCE[0]}" = "${0}" ]; then
    if [ "${1:-}" = "--help" ]; then
        usage
    else
        echo "Linting Bash scripts"
        docker-compose \
            -f docker-compose.ci.yml \
            run --rm --no-deps shellcheck \
            scripts/*

        echo "Executing Scala tests"
        docker-compose \
            run --rm sbt \
            "; scalafix --check; test"
    fi
fi
