#!/bin/bash

set -e

if [[ -n "${GRANARY_DEBUG}" ]]; then
    set -x
fi

function usage() {
    echo -n \
        "Usage: $(basename "$0")
Setup external project dependencies.
"
}

function build_frontend() {
    echo "Building frontend"
    pushd granary-ui
    elm-app make src/Main.elm --output public/index.html
    popd
}

if [ "${BASH_SOURCE[0]}" = "${0}" ]; then
    if [ "${1:-}" = "--help" ]; then
        usage
    elif [ "${1:-}" = "--frontend" ]; then
	build_frontend
    else
	build_frontend

        docker-compose build --pull

        # Bring up PostgreSQL and SBT in a way that respects
        # configured service health checks.
        docker-compose up -d database

	# Pull in development data
	./scripts/load-development-data

        # Apply any outstanding migrations.
        docker-compose \
            -f docker-compose.yml \
            run --rm \
            api-migrations migrate

        # Remove service associated with `docker-compose up`
        # command above.
        docker-compose kill api &&
            docker-compose rm -f api
    fi
fi
