#!/bin/bash

set -e

if [[ -n "${GRANARY_DEBUG}" ]]; then
    set -x
fi

function usage() {
    echo -n \
        "Usage: $(basename "$0")
Setup external project dependencies.
"
}

if [ "${BASH_SOURCE[0]}" = "${0}" ]; then
    if [ "${1:-}" = "--help" ]; then
        usage
    else
        docker-compose build --pull

        echo "Building Scala assembly JAR"
        docker-compose \
            run --rm --no-deps sbt \
            api/assembly

        # Bring up PostgreSQL and SBT in a way that respects
        # configured service health checks.
        docker-compose up -d database app-backend

        # Apply any outstanding migrations.
        docker-compose \
            -f docker-compose.yml \
            run --rm \
            app-backend-migrations migrate

        # Remove service associated with `docker-compose up`
        # command above.
        docker-compose kill app-backend &&
            docker-compose rm -f app-backend
    fi
fi
